matrix:
  include:
    - name: Android Build
      language: android
      cache:
        bundler: true
        directories:
          - $HOME/.pub-cache
      android:
        components:
          - build-tools-28.0.3
          - android-28
        licenses:
          - 'android-sdk-license-.+'
      before_script:
        - openssl aes-256-cbc -K $encrypted_1fe07e098b28_key -iv $encrypted_1fe07e098b28_iv -in secrets.tar.enc -out secrets.tar -d
        - tar xvf secrets.tar
        - git clone https://github.com/flutter/flutter.git -b stable
        - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
        - gem install bundler && cd android && bundle install && cd ..
      script:
        - flutter packages get
        - flutter build apk
        - cd android && bundle exec fastlane internal